name = "lapce-haxe"
version = "0.0.0"
author = "tobil4sk"
display-name = "Haxe"
description = "Haxe LSP support"
wasm = "bin/lapce-haxe.wasm"

[activation]
language = ["haxe"]
workspace-contains = ["*.hxml"]

[config."volt.serverPath"]
default = ""
description = "Path to custom LSP executable"

# [config."volt.serverArgs"]
# default = []
# description = ""

# [config."lspSettingArray"]
# default = []
# description = ""

# [config."lspSettingString"]
# default = ""
# description = ""

# [config."lspSettingBool"]
# default = false
# description = ""
